### PR TITLE
Fix lint errors

### LINKED ISSUE #18: Fix for loops so that they don't use "for in" syntax. You should be able to get no linter errors after this step.

### PR DESCRIPTION
**Pull request by amysorto**

### CODE REVIEW

File: src/components/LineChart/LineChart.jsx [hunk 1]
```diff
@@ -517,6 +531,7 @@ class LineChart extends PureComponent {
       },
     ];
     // Append annotation to the graph
+    // eslint-disable-next-line import/no-named-as-default-member
```
Comment (jacquigiese) [inline src/components/LineChart/LineChart.jsx]: Would fixing this lint error involve redux? Is that why it is being disabled?

Comment (amysorto) [reply src/components/LineChart/LineChart.jsx]: I did this because when I tried separating out this logic, nothing was being rendered. I assumed it was maybe a svgAnnotation thing so I added the eslint-diable. Not sure how to fix this otherwise.

File: src/containers/LocationPage/LocationPage.jsx [hunk 2]
```diff
@@ -433,8 +435,8 @@ class LocationPage extends PureComponent {
 
     // Create ASN Number to ISP Object dictionary
     const asnToISPObj = {};
-    for (const currIsp in topClientIsps) {
-      asnToISPObj[topClientIsps[currIsp].client_asn_number] = topClientIsps[currIsp];
+    for (let currIspIndex = 0; currIspIndex < topClientIsps.length; currIspIndex++) {
```
Comment (jacquigiese) [inline src/containers/LocationPage/LocationPage.jsx]: Perhaps change this variable name to ispIndex so that it is a little shorter and more consistent with other variables like the asnIndex!

**Review by jacquigiese — APPROVED** [review]
Made one comment that's a nitpick, but otherwise looks good!

File: src/components/LineChart/LineChart.jsx (hunk 1 above)
Comment (roman-rosenast) [reply src/components/LineChart/LineChart.jsx]: This seems like something that should be addressed.

File: src/containers/LocationPage/LocationPage.jsx (hunk 2 above)
Comment (roman-rosenast) [reply src/containers/LocationPage/LocationPage.jsx]: Agreed. Also I commend you for fixing all these for loops' syntax!

**Review by roman-rosenast — CHANGES_REQUESTED** [review]
Looks good, the only really noteworthy thing is that svgAnnotation comment which probably just requires some tinkering to resolve. I'm happy to help ya with it in our work session if you want.

**Review by roman-rosenast — APPROVED** [review]
Good work!
